### ISSUE TITLE
python-mode required for each python file being opened

### ISSUE THREAD

**Issue by Mafeuser** [stotok/dotspacemacs#1]
Hi stotok

I'm trying python mode (ttk-elpy) from Your config.

When I'm trying to open python file I get following message:
"Support for python-mode requires installation of layer python, do You want to install it? (y or n)"

I press "n" of course, then I end up in python buffer and both completion and elpy works fine.

This message occurs for every python file, which might be quite annoying after a few files opened. Do You experience the same behavour?

regards

**Comment by stotok** [comment]
Hi Mafeuser

Sorry I just be able to get back here because I was busy with other project.

Yeah, I experience the same behavior as yours. The annoying message, though, does not appear if there is shebang line in python file.

I'll take a look on it.

Thanks.

**Comment by stotok** [comment]
Hi ,, I just be able to come back to this issue ,,,, the fix is to disable lazy installation by setting    

`
dotspacemacs-enable-lazy-installation 'nil
`

in .spacemacs :)

**Comment by Mafeuser** [comment]
thanks for help!

In the meantime I've worked out the solution if one does not want to loose functionality of lazy layers installation for other extensions:

```
(assq-delete-all 'python-mode configuration-layer--lazy-mode-alist)
(delete-if (lambda (elem) (string-equal "\\(\\.py\\'\\)" (car elem))) auto-mode-alist)
```

best regards,
Mat

**Comment by stotok** [comment]
Hi Mat,

Thanks for your feedback and with your solution. Yeah, not loosing functionality of other ext lazy layers is good idea.

I'll try it. And I'll put your fix into my config.

Appreciate your help,
stotok
